version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Set reviewers for pull requests
    reviewers:
      - "team-maintainers"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "security"
    # Set the version requirement update strategy
    # Supported options: widen, increase, increase-if-necessary
    versioning-strategy: increase-if-necessary
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Add security vulnerability checks
    security-updates-only: false
    # Ignore certain dependencies (example)
    # ignore:
    #   - dependency-name: "express"
    #     versions: ["4.x.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
