module.exports = {
	preset: 'ts-jest',
	testEnvironment: 'node',
	roots: ['<rootDir>/src'],
	testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
	transform: {
		'^.+\\.ts$': 'ts-jest',
	},
	moduleFileExtensions: ['ts', 'js', 'json', 'node'],
	collectCoverage: true,
	coverageDirectory: 'coverage',
	collectCoverageFrom: [
		'src/**/*.ts',
		'!src/**/*.d.ts',
		'!src/**/*.interface.ts',
		'!src/types/**/*.ts',
		'!src/controller/**/*.ts',
		'!src/middleware/**/*.ts',
		'!src/migrations/**/*.ts',
		'!src/routes/**/*.ts',
		'!src/schema/**/*.ts',
		'!src/test/**/*.ts',
		'!src/upload/**/*.ts',
		'!src/app.ts',
		'!src/test-feature-flags.ts',
		'!src/test-logger.ts',
	],
	coverageThreshold: {
		global: {
			branches: 7,
			functions: 8,
			lines: 13,
			statements: 13,
		},
	},
	moduleNameMapper: {
		'^@const/(.*)$': '<rootDir>/src/const/$1',
		'^@controllers/(.*)$': '<rootDir>/src/controller/$1',
		'^@entities/(.*)$': '<rootDir>/src/entities/$1',
		'^@middleware/(.*)$': '<rootDir>/src/middleware/$1',
		'^@migrations/(.*)$': '<rootDir>/src/migrations/$1',
		'^@repository/(.*)$': '<rootDir>/src/repository/$1',
		'^@routes/(.*)$': '<rootDir>/src/routes/$1',
		'^@schema/(.*)$': '<rootDir>/src/schema/$1',
		'^@service/(.*)$': '<rootDir>/src/service/$1',
		'^@types/(.*)$': '<rootDir>/src/types/$1',
		'^@upload/(.*)$': '<rootDir>/src/upload/$1',
		'^@utils/(.*)$': '<rootDir>/src/utils/$1',
		'^@views/(.*)$': '<rootDir>/src/views/$1',
	},
};
